import pygame


# window size
WINDOW_WIDTH = 364
WINDOW_HEIGHT = 450
WINDOWS_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

# board size
BOARD_WIDTH = 332
BOARD_HEIGHT = 332
BOARD_BORDER = 20
BOARD_MARGIN = (WINDOW_WIDTH - BOARD_WIDTH) / 2
BOARD_POS = (BOARD_MARGIN, WINDOW_HEIGHT - BOARD_HEIGHT - BOARD_MARGIN)
BOARD_SIZE = (BOARD_WIDTH, BOARD_HEIGHT)
BOARD_CELL_SIZE = (4, 4)

# tile size
TILE_WIDTH = BOARD_WIDTH // BOARD_CELL_SIZE[0]
TILE_HEIGHT = BOARD_HEIGHT // BOARD_CELL_SIZE[1]
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)

# time
FPS = 60
FRAME_MS = 1000 // FPS

# colors
SCENE_BACKGROUND_COLOR = pygame.Color("#102526")
HUD_DEFAULT_COLOR = pygame.Color("#18494BEE")

# fonst
FONT_LARGE = None
FONT_SMALL = None
FONT_DEFAULT_COLOR = (255, 255, 255)
FONT_NAME = "data/fonts/Roboto-Medium.ttf"
FONT_LARGE_SIZE = 32
FONT_SMALL_SIZE = 12


def init():
    global FONT_LARGE
    global FONT_SMALL
    FONT_LARGE = pygame.font.Font(FONT_NAME, FONT_LARGE_SIZE)
    FONT_SMALL = pygame.font.Font(FONT_NAME, FONT_SMALL_SIZE)
